import type { Event } from "@/lib/types";
import { generateEventSummary, generateSubEventSummary } from "@/lib/ai";

function withAi(events: Event[]): Event[] {
  return events.map((e) => ({
    ...e,
    aiSummary: e.aiSummary ?? generateEventSummary(e),
    subEvents: e.subEvents.map((s) => ({ ...s, aiSummary: s.aiSummary ?? generateSubEventSummary(s) })),
  }));
}

const raw: Event[] = [
  {
    id: "evt-boston-college",
    title: "Got into Boston College",
    category: "both",
    date: "2025-03-14",
    description: "Opened my acceptance letter after months of applications and waiting.",
    significance: 5,
    visibility: "portfolio",
    skills: ["Resilience", "Goal-Setting"],
    subEvents: [
      {
        id: "sub-bc-essay",
        parentEventId: "evt-boston-college",
        title: "Finished the personal essay",
        date: "2025-01-10",
        description: "Rewrote my essay five times until it finally sounded like me.",
        whyItMattered: "Taught me to keep revising instead of settling for a first draft",
        significance: 3,
        skillTags: ["Communication", "Persistence"],
      },
      {
        id: "sub-bc-interview",
        parentEventId: "evt-boston-college",
        title: "Alumni interview",
        date: "2025-02-02",
        description: "Sat down with a BC alum and actually enjoyed the conversation.",
        whyItMattered: "Realized I could talk about myself without over-preparing a script",
        significance: 2,
        skillTags: ["Communication", "Confidence"],
      },
    ],
  },
  {
    id: "evt-marathon",
    title: "Ran First Marathon",
    category: "personal",
    date: "2025-05-04",
    description: "Crossed the finish line after a year of training through injuries and doubt.",
    significance: 5,
    visibility: "portfolio",
    skills: ["Resilience", "Discipline"],
    subEvents: [
      {
        id: "sub-marathon-injury",
        parentEventId: "evt-marathon",
        title: "Came back from a knee injury",
        date: "2025-02-20",
        description: "Spent six weeks doing physical therapy instead of running.",
        whyItMattered: "Learned patience is part of training, not separate from it",
        significance: 3,
        skillTags: ["Resilience", "Patience"],
      },
      {
        id: "sub-marathon-20mi",
        parentEventId: "evt-marathon",
        title: "First 20-mile training run",
        date: "2025-04-12",
        description: "Ran 20 miles solo before sunrise and didn't quit.",
        whyItMattered: "Proved to myself I could finish what I started, even alone",
        significance: 4,
        skillTags: ["Discipline", "Resilience"],
      },
    ],
  },
  {
    id: "evt-python",
    title: "Built First Python Project",
    category: "professional",
    date: "2024-11-08",
    description: "Shipped a small CLI tool that scrapes and organizes my class schedule.",
    significance: 3,
    visibility: "private",
    skills: ["Technical Skill", "Problem-Solving"],
    subEvents: [
      {
        id: "sub-python-bug",
        parentEventId: "evt-python",
        title: "Debugged a stubborn parsing error",
        date: "2024-11-05",
        description: "Spent three hours tracking down a silent off-by-one bug.",
        whyItMattered: "Finally understood how to actually read a stack trace",
        significance: 2,
        skillTags: ["Technical Skill", "Problem-Solving"],
      },
      {
        id: "sub-python-ship",
        parentEventId: "evt-python",
        title: "Shared it with three classmates",
        date: "2024-11-08",
        description: "Sent the tool to friends and watched them actually use it.",
        whyItMattered: "First time something I built was useful to someone else",
        significance: 3,
        skillTags: ["Technical Skill", "Communication"],
      },
    ],
  },
  {
    id: "evt-internship",
    title: "Internship at ABC Corp",
    category: "professional",
    date: "2025-06-01",
    description: "Spent the summer as a software intern on the data platform team.",
    significance: 5,
    visibility: "portfolio",
    skills: ["Technical Skill", "Leadership", "Communication"],
    subEvents: [
      {
        id: "sub-intern-pr",
        parentEventId: "evt-internship",
        title: "Shipped first PR",
        date: "2025-06-10",
        description: "Merged a small bug fix into the production pipeline.",
        whyItMattered: "Realized my code could matter outside of school assignments",
        significance: 3,
        skillTags: ["Technical Skill"],
      },
      {
        id: "sub-intern-demo",
        parentEventId: "evt-internship",
        title: "Gave demo to the team",
        date: "2025-07-15",
        description: "Presented my feature to the full engineering team on a Friday demo day.",
        whyItMattered: "Got over my fear of presenting technical work live",
        significance: 4,
        skillTags: ["Leadership", "Communication"],
      },
      {
        id: "sub-intern-mentee",
        parentEventId: "evt-internship",
        title: "Mentored a newer intern",
        date: "2025-08-01",
        description: "Helped a second-year intern get unblocked on their onboarding project.",
        whyItMattered: "First time I was the one teaching instead of learning",
        significance: 4,
        skillTags: ["Leadership"],
      },
    ],
  },
  {
    id: "evt-sister",
    title: "Reconciled with Sister",
    category: "personal",
    date: "2025-01-20",
    description: "Had the hard conversation we'd both been avoiding for months.",
    significance: 4,
    visibility: "private",
    skills: ["Communication", "Emotional Growth"],
    subEvents: [
      {
        id: "sub-sister-call",
        parentEventId: "evt-sister",
        title: "Made the first call",
        date: "2025-01-18",
        description: "Texted her first instead of waiting for her to reach out.",
        whyItMattered: "Realized pride was the only thing keeping the silence going",
        significance: 3,
        skillTags: ["Emotional Growth"],
      },
    ],
  },
];

export const seedEvents: Event[] = withAi(raw);
